---
# https://github.com/major/MySQLTuner-perl

- git:
    repo: git@github.com:major/MySQLTuner-perl.git
    dest: '{{ ansible_user_dir }}/src/my-sql-tuner'
  when: git.protocol == 'ssh'

- git:
    repo: https://github.com/major/MySQLTuner-perl.git
    dest: '{{ ansible_user_dir }}/src/my-sql-tuner'
  when: git.protocol == 'https'

- apt:
    name: mysqltuner
  remote_user: root
  when: ansible_os_family == 'Debian'
